name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  # Network & API
  retrofit: ^4.1.0
  dio: ^5.4.0
  json_annotation: ^4.9.0

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.0
  path_provider: ^2.1.1

  # Utils
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation tools
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  retrofit_generator: ^8.1.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
