import 'package:json_annotation/json_annotation.dart';

part 'api_note.g.dart';

// ApiNote - data transfer object for JSONPlaceholder API communication
@JsonSerializable() // Enables automatic JSON serialization/deserialization via code generation
class ApiNote {
  final int? id; // API-generated integer ID (nullable for POST requests)
  final String? title; // Note title (nullable to match API response structure)
  final String? body; // Note content (nullable to match API response structure)

  ApiNote({
    this.id,
    this.title,
    this.body,
  });

  // JSON deserialization - automatically generated by json_serializable package
  factory ApiNote.fromJson(Map<String, dynamic> json) => _$ApiNoteFromJson(json);

  // JSON serialization - automatically generated by json_serializable package
  Map<String, dynamic> toJson() => _$ApiNoteToJson(this);
}